name: Build and Release

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        label: [
          x86_64-pc-windows-msvc-portable
          ]
        include:
          - label: x86_64-pc-windows-msvc-portable
            target: x86_64-pc-windows-msvc
            bins: --bin juliaup --bin julia
            os: windows
            features: binjulialauncher
            rustflags:
            toolchain: stable
    steps:
    # - uses: actions/checkout@v4
    - name: Clone juliaup repo
      run: |
        git clone https://github.com/JuliaLang/juliaup
        # pwd
        # tree
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{matrix.toolchain}}
        default: true
        target: ${{matrix.target}}
    - name: Release build
      run: |
        cd juliaup
        cargo build --release ${{matrix.bins}} --target ${{matrix.target}}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.label}}
        path: |
          juliaup/target/${{matrix.target}}/release/juliaup.exe
          juliaup/target/${{matrix.target}}/release/julia.exe
        # NOTICE! I do not know how to set the working directory in a step.
        # If use `run` instead of `uses actions/*`, can use `cd juliaup`,
        # but here use the `juliaup` prefix.
        # working-directory: juliaup

  package-portable:
    needs: [build]
    environment: package
    runs-on: ubuntu-latest
    steps:
    - name: Download x86_64-pc-windows-msvc-portable artifact
      uses: actions/download-artifact@v3
      with:
        name: x86_64-pc-windows-msvc-portable
        path: target/x86_64-pc-windows-msvc-portable
    - name: Create archives
      run: |
        cd julia
        mkdir public
        cd target/x86_64-pc-windows-msvc-portable
        zip -r ../../public/juliaup-${{ env.VERSION }}-x86_64-pc-windows-msvc-portable.zip .
        cd ../..
    - uses: actions/upload-artifact@v3
      with:
        name: portable
        path: public/*.*

  deploy-github-release-binaries:
    needs: [package-portable]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: portable
        path: public
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "public/*.*"
        allowUpdates: true
        prerelease: false
