name: Build and Release

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 0 1 * *'

jobs:

  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        label: [
          x86_64-pc-windows-msvc-portable
          ]
        include:
          - label: x86_64-pc-windows-msvc-portable
            target: x86_64-pc-windows-msvc
            bins: --bin juliaup --bin julia
            os: windows
            features: binjulialauncher
            rustflags:
            toolchain: stable
    steps:
    # - uses: actions/checkout@v4
    - name: Clone juliaup repo
      run: |
        git clone https://github.com/JuliaLang/juliaup --depth=1
        # pwd
        # tree
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{matrix.toolchain}}
        default: true
        target: ${{matrix.target}}
    - name: Release build
      # Here was an action: clechasseur/rs-cargo
      run: |
        cd juliaup
        cargo build --release ${{matrix.bins}} --target ${{matrix.target}}
    - uses: actions/upload-artifact@v3
      # NOTICE! I do not know how to set the working directory in a step.
      # If use `run` instead of `uses actions/*`, can use `cd xxx`.
      # Here use the `juliaup` prefix.
      with:
        name: ${{matrix.label}}
        path: |
          juliaup/target/${{matrix.target}}/release/juliaup.exe
          juliaup/target/${{matrix.target}}/release/julia.exe
        # working-directory: juliaup

  package-portable:
    needs: [build]
    environment: package
    runs-on: ubuntu-latest
    steps:
    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +%Y%m%d)"
    - name: Download x86_64-pc-windows-msvc-portable artifact
      uses: actions/download-artifact@v3
      with:
        name: x86_64-pc-windows-msvc-portable
        path: target/x86_64-pc-windows-msvc-portable
    - name: Create archives
      run: |
        # tree
        mkdir public
        cd target/x86_64-pc-windows-msvc-portable
        zip -r ../../public/juliaup-${{ steps.date.outputs.date }}-x86_64-pc-windows-msvc-portable.zip .
        cd ../..
    - uses: actions/upload-artifact@v3
      with:
        name: portable
        path: public/*.*

  deploy-github-release-binaries:
    needs: [package-portable]
    runs-on: ubuntu-latest
    steps:
    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +%Y%m%d)"
    - uses: actions/download-artifact@v3
      with:
        name: portable
        path: public
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "public/*.*"
        allowUpdates: true
        prerelease: false
        tag: ${{ steps.date.outputs.date }}
