name: Build and Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'

jobs:

  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        label: [
          x86_64-pc-windows-msvc-portable
          ]
        include:
          - label: x86_64-pc-windows-msvc-portable
            target: x86_64-pc-windows-msvc
            bins: --bin juliaup --bin julia
            os: windows
            features: binjulialauncher
            rustflags:
            toolchain: stable
    outputs:
      tag-changed: ${{ steps.compare-tags.outputs.tag-changed }}
      tag: ${{ steps.repo-latest-tag.outputs.tag }}
    steps:
    # - uses: actions/checkout@v4
    - name: Clone juliaup repo
      run: |
        git clone https://github.com/JuliaLang/juliaup
        # pwd
        # tree
    - name: Get latest tag
      id: repo-latest-tag
      run: |
        cd juliaup
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get latest release tag
      id: release-latest-tag
      run: |
        RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/latest")
        LATEST_TAG=$(echo "$RESPONSE" | jq -r '.tag_name')
        echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compare tags
      id: compare-tags
      run: |
        LATEST_TAG_GITHUB=$(echo "${{ steps.repo-latest-tag.outputs.tag }}" | sed 's/v//')
        LATEST_TAG_RELEASE=$(echo "${{ steps.release-latest-tag.outputs.tag }}" | sed 's/v//')
        if [[ "$LATEST_TAG_GITHUB" == "$LATEST_TAG_RELEASE" ]]; then
          echo "tag-changed=false" >> $GITHUB_OUTPUT
          exit 1
        else
          echo "tag-changed=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{matrix.toolchain}}
        default: true
        target: ${{matrix.target}}

    - name: Release build
      # Here was an action: clechasseur/rs-cargo
      run: |
        cd juliaup
        cargo build --release ${{matrix.bins}} --target ${{matrix.target}}

    - uses: actions/upload-artifact@v4
      # NOTICE! I do not know how to set the working directory in a step.
      # If use `run` instead of `uses actions/*`, can use `cd xxx`.
      # Here use the `juliaup` prefix.
      with:
        name: ${{matrix.label}}
        path: |
          juliaup/target/${{matrix.target}}/release/juliaup.exe
          juliaup/target/${{matrix.target}}/release/julia.exe
        # working-directory: juliaup

  package-portable:
    needs: [build]
    if: needs.build.outputs.tag-changed == 'true'
    environment: package
    runs-on: ubuntu-latest
    steps:
    - name: Download x86_64-pc-windows-msvc-portable artifact
      uses: actions/download-artifact@v4
      with:
        name: x86_64-pc-windows-msvc-portable
        path: target/x86_64-pc-windows-msvc-portable
    - name: Create archives
      run: |
        # tree
        mkdir public
        cd target/x86_64-pc-windows-msvc-portable
        zip -r ../../public/juliaup-${{ needs.build.outputs.tag }}-x86_64-pc-windows-msvc-portable.zip .
        cd ../..
    - uses: actions/upload-artifact@v4
      with:
        name: portable
        path: public/*.*

  deploy-github-release-binaries:
    needs: [build, package-portable]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: portable
        path: public
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "public/*.*"
        allowUpdates: true
        prerelease: false
        tag: ${{ needs.build.outputs.tag }}
